# Generated by Django 4.2.11 on 2024-04-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низкий'), ('Middle', 'Средний'), ('High', 'Высокий')], default='Middle', max_length=50),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низкий'), ('Middle', 'Средний'), ('High', 'Высокий')], default='Middle', max_length=50),
        ),
    ]
